---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-deployment-concourse-tasks
inputs:
- name: cf-deployment-develop
params:
  GITHUB_TOKEN:
  GITHUB_REPO:
  WORKFLOW_FILE:
  WORKFLOW_REF: main
  WORKFLOW_INPUTS: "{}"
run:
  path: cf-deployment-develop/ci/tasks/trigger-github-workflow/task.sh
