#!/bin/bash

set -e -x

pushd $(dirname $0)
  SCRIPT_DIR=$(pwd)
popd

RELEASE_DIR=${SCRIPT_DIR}/../outputs/releases
rm -rf ${RELEASE_DIR}
mkdir -p ${RELEASE_DIR}

OUTPUT_DIR=${SCRIPT_DIR}/../outputs/create_release
rm -rf ${OUTPUT_DIR}
mkdir -p ${OUTPUT_DIR}

if [ $# -ne 2 ]; then
  echo "Usage: create_releases PATH_TO_CF_RELEASE PATH_TO_ETCD_RELEASE"
  exit 1
fi

CF_RELEASE_PATH=$1
ETCD_RELEASE_PATH=$2

if [ ! -d ${CF_RELEASE_PATH} ]; then
  echo "PATH_TO_CF_RELEASE is invalid"
  exit 1
fi

if [ ! -d ${ETCD_RELEASE_PATH} ]; then
  echo "PATH_TO_ETCD_RELEASE is invalid"
  exit 1
fi

pushd ${CF_RELEASE_PATH}
  bosh -n create release --force --name cf --with-tarball 2>&1 | tee ${OUTPUT_DIR}/cf.out
  EXIT_STATUS=${PIPESTATUS[0]}

  if [ ! ${EXIT_STATUS} -eq 0 ]; then
    echo "Failed to create cf release"
    exit 1
  fi

  CF_RELEASE_TARBALL=$(grep "Release tarball" ${OUTPUT_DIR}/cf.out | sed 's/.*: //')

  mv ${CF_RELEASE_TARBALL} ${RELEASE_DIR}
popd

pushd ${ETCD_RELEASE_PATH}
  bosh -n create release --force --name etcd --with-tarball 2>&1 | tee ${OUTPUT_DIR}/etcd.out
  EXIT_STATUS=${PIPESTATUS[0]}

  if [ ! ${EXIT_STATUS} -eq 0 ]; then
    echo "Failed to create etcd release"
    exit 1
  fi

  ETCD_RELEASE_TARBALL=$(grep "Release tarball" ${OUTPUT_DIR}/etcd.out | sed 's/.*: //')

  mv ${ETCD_RELEASE_TARBALL} ${RELEASE_DIR}
popd
