#!/bin/bash

set -euf -o pipefail

CF_DEPLOYMENT_TRACE=${CF_DEPLOYMENT_TRACE:-}
if [ ! -z "${CF_DEPLOYMENT_TRACE}" ]; then
  set -x
fi

mydir="$(cd "$(dirname "$0")" && pwd)"

STUBS_DIR=${mydir}/../stubs

if [ $# -lt 3 ]; then
  echo "Usage: generate_deployment_manifest <aws|openstack|warden|vsphere> PATH_TO_CF_RELEASE [stubs...]"
  exit 1
fi

INFRASTRUCTURE=$1
CF_RELEASE_PATH=$2

shift
shift
if [ ! -d "${CF_RELEASE_PATH}" ]; then
  echo "PATH_TO_CF_RELEASE is invalid"
  exit 1
fi

"${CF_RELEASE_PATH}/scripts/generate_deployment_manifest" \
  "${INFRASTRUCTURE}" \
  "${STUBS_DIR}/job_templates.yml" \
  "$@"
