#!/bin/bash

set -euf -o pipefail

CF_DEPLOYMENT_TRACE=${CF_DEPLOYMENT_TRACE:-}
if [ ! -z "${CF_DEPLOYMENT_TRACE}" ]; then
  set -x
fi

mydir="$(cd "$(dirname "$0")" && pwd)"
templates_dir="$(cd "${mydir}/../templates" && pwd )"

if [ $# -lt 3 ]; then
  echo "Usage: generate_deployment_manifest <aws|openstack|warden|vsphere> CF_RELEASE_PATH [stubs...]"
  exit 1
fi

INFRASTRUCTURE=$1
CF_RELEASE_PATH=$2

shift
shift
if [ ! -d "${CF_RELEASE_PATH}" ]; then
  echo "CF_RELEASE_PATH is invalid"
  exit 1
fi

"${CF_RELEASE_PATH}/scripts/generate_deployment_manifest" \
  "${INFRASTRUCTURE}" \
  "${templates_dir}/job_templates.yml" \
  "$@"
