#!/bin/bash

set -e

pushd $(dirname $0) > /dev/null
  SCRIPT_DIR=$(pwd)
popd > /dev/null

STUBS_DIR=${SCRIPT_DIR}/../stubs

if [ $# -lt 3 ]; then
  echo "Usage: generate_deployment_manifest <aws|openstack|warden|vsphere> PATH_TO_CF_RELEASE [stubs...]"
  exit 1
fi

INFRASTRUCTURE=$1
CF_RELEASE_PATH=$2

shift
shift

if [ ! -d ${CF_RELEASE_PATH} ]; then
  echo "PATH_TO_CF_RELEASE is invalid"
  exit 1
fi

${CF_RELEASE_PATH}/scripts/generate_deployment_manifest ${INFRASTRUCTURE} ${STUBS_DIR}/releases.yml ${STUBS_DIR}/job_templates.yml $@
