#!/bin/bash

set -e -x

pushd $(dirname $0) > /dev/null
  SCRIPT_DIR=$(pwd)
popd > /dev/null

STUBS_DIR=${SCRIPT_DIR}/../stubs

if [ $# -lt 5 ]; then
  echo "Usage: prepare_deployment <aws|openstack|warden|vsphere> PATH_TO_CF_RELEASE PATH_TO_ETCD_RELEASE PATH_TO_CONSUL_RELEASE [stubs...]"
  exit 1
fi

INFRASTRUCTURE=$1
CF_RELEASE_PATH=$2
ETCD_RELEASE_PATH=$3
CONSUL_RELEASE_PATH=$4

shift
shift
shift
shift

${SCRIPT_DIR}/create_releases ${CF_RELEASE_PATH} ${ETCD_RELEASE_PATH} ${CONSUL_RELEASE_PATH} 1>&2

${SCRIPT_DIR}/generate_deployment_manifest ${INFRASTRUCTURE} ${CF_RELEASE_PATH} $@ ${STUBS_DIR}/versions.yml
