#!/bin/bash -eu

function suites() {
  local suites
  suites="
    ./tests/addons_test
    ./tests/backup_and_restore_test
    ./tests/experimental_test
    ./tests/iaas_test
    ./tests/inline_test
    ./tests/standard_test
    ./tests/test_test
    ./tests/semantic_test
    "

  echo "${suites}"
}

pushd "$(dirname "$0")" > /dev/null
  if [ ! -f "test-vars-store.yml" ]; then
    echo "Generating vars-store..."
    bosh interpolate ../cf-deployment.yml --vars-store test-vars-store.yml > /dev/null
  fi

  echo "Starting unit tests..."
  go test "$@" $(suites) -timeout=20m
popd > /dev/null
